### ISSUE TITLE
Apimties praplėtimas

### ISSUE THREAD

**Issue by pppss102** [nmakademija/inf-knyga#12]
Šiuo metu knyga apima tik pačias primityviausias [IOI (ir tuo pačiu LMIO) kurso](https://ioinformatics.org/files/ioi-syllabus-2024.pdf) dalis, ar būtų įmanoma praplėsti /prisidėti-prie praplėtimo iki pilno/beveik-pilnoko IOI kurso padengimo, taip nepaliekant moksleivių daugmaž ant ledo mokantis toliau (apie tolimesnį mokymąsi suteikiama 0 informacijos (nebent kažką praleidau)) - būtų gan šaunu turėti vieningą ir bent kažkiek patikimą informacijos šaltinį.

**Comment by vakaras** [comment]
Kaip sakoma: „PRs are welcome“.

**Comment by pppss102** [comment]
> Kaip sakoma: „PRs are welcome“.

Šaunu, tik norėjau pasitikslinti; artimiausiu metu pabandysiu paruošti kažką pusiau suprantamo :)
